# Generated by Django 4.2 on 2023-04-18 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teste',
        ),
    ]
