# Generated by Django 4.2 on 2023-04-18 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_delete_teste'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='data_sorteio',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
