# Generated by Django 4.2 on 2023-04-18 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_pessoa_data_sorteio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='data_sorteio',
        ),
        migrations.AddField(
            model_name='pessoa',
            name='escolhido',
            field=models.BooleanField(default=False),
        ),
    ]
