# Generated by Django 4.2 on 2023-04-18 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_pessoa_data_sorteio_pessoa_escolhido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='data',
            field=models.DateField(null=True),
        ),
    ]
