# Generated by Django 4.2 on 2023-04-18 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_pessoa_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='data',
            field=models.DateField(blank=True, null=True),
        ),
    ]
