# Generated by Django 4.2 on 2023-04-21 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_pessoa_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
